CREATE TABLE Actor(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) NOT NULL UNIQUE,
	age int CHECK (age > 0)
);

CREATE TABLE Movie(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar(200) NOT NULL,
	year_of_production int CHECK (year_of_production > 1900)
);

-- Create join table

CREATE TABLE Actor_Movie(
	actor_id int REFERENCES Actor(id),
	movie_id int REFERENCES Movie(id),
	PRIMARY KEY(actor_id, movie_id)
);